import {
  catalogProviderModels,
  normalizeCatalog,
  type Catalog,
  type CatalogModel,
} from '@yaseenhq/tsugite';

import {
  CUSTOM_REGISTRY_MODEL_FIELDS,
  mergeRefreshedModelAlias,
} from './model-alias-merge';
import type {
  ManagedKimiConfigShape,
  ManagedKimiModelAlias,
} from './managed-kimi-code';
import { isRecord } from './utils';

/** The public models.dev catalog. Used to infer provenance for providers that
 * predate the `source` stamp, or were created by a flow that never wrote one
 * (OAuth logins). */
export const MODELS_DEV_CATALOG_URL = 'https://models.dev/api.json';

/** Provenance written by the known-provider models.dev importer. */
export interface ModelsDevSource {
  readonly kind: 'modelsDev';
  readonly url: string;
  readonly catalogId: string;
  readonly [key: string]: unknown;
}

export interface FetchModelsDevCatalogOptions {
  readonly signal?: AbortSignal;
  readonly fetchImpl?: typeof fetch;
  readonly userAgent?: string;
}

/**
 * Fields owned by models.dev for aliases imported from its catalog. Fields not
 * in this set remain user-owned and are carried across a refresh. `overrides`
 * is handled separately by `mergeRefreshedModelAlias` and therefore remains
 * user-owned as well.
 */
const MODELS_DEV_MODEL_FIELDS: ReadonlySet<string> = new Set([
  ...CUSTOM_REGISTRY_MODEL_FIELDS,
  'maxInputSize',
  'reasoningKey',
  'offEffort',
  'protocol',
  'baseUrl',
]);

/**
 * Provenance for a provider, inferring it when absent.
 *
 * Only the API-key catalog import stamps `source`; an OAuth login never does,
 * so providers like `xai` carried no provenance and were skipped by the
 * refresh entirely — new upstream models never reached them. When the id
 * matches a models.dev catalog entry, treat it as models.dev-backed so the
 * catalog stays the single place new models come from, whatever the auth.
 */
export function resolveModelsDevSource(
  provider: unknown,
  providerId: string,
  catalogIds: ReadonlySet<string>,
): ModelsDevSource | undefined {
  const declared = readModelsDevSource(provider);
  if (declared !== undefined) return declared;
  if (!catalogIds.has(providerId)) return undefined;
  return { kind: 'modelsDev', url: MODELS_DEV_CATALOG_URL, catalogId: providerId };
}

export function readModelsDevSource(provider: unknown): ModelsDevSource | undefined {
  const source = isRecord(provider) ? provider['source'] : undefined;
  if (!isRecord(source) || source['kind'] !== 'modelsDev') return undefined;
  const url = source['url'];
  const catalogId = source['catalogId'];
  if (typeof url !== 'string' || url.length === 0) return undefined;
  if (typeof catalogId !== 'string' || catalogId.length === 0) return undefined;
  return source as ModelsDevSource;
}

/** Fetch and normalize one models.dev-shaped catalog. */
export async function fetchModelsDevCatalog(
  source: ModelsDevSource,
  options: FetchModelsDevCatalogOptions = {},
): Promise<Catalog> {
  const headers: Record<string, string> = { Accept: 'application/json' };
  if (options.userAgent !== undefined) headers['User-Agent'] = options.userAgent;
  const response = await (options.fetchImpl ?? fetch)(source.url, {
    headers,
    ...(options.signal === undefined ? {} : { signal: options.signal }),
  });
  if (!response.ok) {
    throw new Error(`models.dev catalog returned HTTP ${String(response.status)}`);
  }
  return normalizeCatalog(await response.json());
}

/**
 * Replace the generated aliases for one models.dev provider in memory.
 *
 * Aliases using the conventional `<providerId>/...` prefix are generated by
 * the importer and are reconciled (including removals). Other aliases for the
 * same provider are user-owned and remain untouched. Remote metadata is
 * merged field-by-field so local aliases and explicit `overrides` survive.
 */
export function applyModelsDevProviderModels(
  config: ManagedKimiConfigShape,
  providerId: string,
  models: readonly CatalogModel[],
): void {
  const aliases = config.models ?? {};
  const prefix = `${providerId}/`;
  const upstreamKeys = new Set(models.map((model) => `${providerId}/${model.id}`));

  for (const [alias, raw] of Object.entries(aliases)) {
    if (
      !isRecord(raw) ||
      raw['provider'] !== providerId ||
      !alias.startsWith(prefix) ||
      upstreamKeys.has(alias)
    ) {
      continue;
    }
    delete aliases[alias];
  }

  for (const model of models) {
    const aliasKey = `${providerId}/${model.id}`;
    const existing = isRecord(aliases[aliasKey]) ? aliases[aliasKey] : {};
    aliases[aliasKey] = mergeRefreshedModelAlias(
      existing,
      catalogModelToAlias(providerId, model),
      MODELS_DEV_MODEL_FIELDS,
    );
  }

  config.models = aliases;
}

/** Translate canonical tsugite catalog metadata into the config alias shape. */
function catalogModelToAlias(providerId: string, model: CatalogModel): ManagedKimiModelAlias {
  const capabilities: string[] = [];
  if (model.capability.image_in) capabilities.push('image_in');
  if (model.capability.video_in) capabilities.push('video_in');
  if (model.capability.audio_in) capabilities.push('audio_in');
  if (model.capability.thinking) capabilities.push('thinking');
  if (model.capability.tool_use) capabilities.push('tool_use');
  if (model.capability.dynamically_loaded_tools) capabilities.push('dynamically_loaded_tools');

  const normalizedCapabilities =
    model.alwaysThinking === true
      ? capabilities.map((capability) =>
          capability === 'thinking' ? 'always_thinking' : capability,
        )
      : capabilities;

  return {
    provider: providerId,
    model: model.wireModel ?? model.id,
    maxContextSize: model.capability.max_context_tokens,
    ...(model.capability.max_input_tokens === undefined
      ? {}
      : { maxInputSize: model.capability.max_input_tokens }),
    ...(model.maxOutputSize === undefined ? {} : { maxOutputSize: model.maxOutputSize }),
    ...(normalizedCapabilities.length === 0 ? {} : { capabilities: normalizedCapabilities }),
    ...(model.name === undefined ? {} : { displayName: model.name }),
    ...(model.reasoningKey === undefined ? {} : { reasoningKey: model.reasoningKey }),
    ...(model.supportEfforts === undefined ? {} : { supportEfforts: [...model.supportEfforts] }),
    ...(model.thinkingBudget?.min === undefined
      ? {}
      : { thinkingBudgetMin: model.thinkingBudget.min }),
    ...(model.thinkingBudget?.max === undefined
      ? {}
      : { thinkingBudgetMax: model.thinkingBudget.max }),
    ...(model.defaultEffort === undefined ? {} : { defaultEffort: model.defaultEffort }),
    ...(model.offEffort === undefined ? {} : { offEffort: model.offEffort }),
    ...(model.requestHeaders === undefined ? {} : { requestHeaders: { ...model.requestHeaders } }),
    ...(model.requestBody === undefined ? {} : { requestBody: { ...model.requestBody } }),
    ...(model.protocol === undefined ? {} : { protocol: model.protocol }),
    ...(model.baseUrl === undefined ? {} : { baseUrl: model.baseUrl }),
  };
}

/** Resolve the model rows for a provider, refusing destructive empty updates. */
export function modelsDevProviderModels(
  catalog: Catalog,
  source: ModelsDevSource,
): readonly CatalogModel[] {
  const entry = catalog[source.catalogId];
  if (entry === undefined) {
    throw new Error(`models.dev catalog does not contain provider ${source.catalogId}`);
  }
  const models = catalogProviderModels(entry);
  if (models.length === 0) {
    throw new Error(`models.dev provider ${source.catalogId} has no usable models`);
  }
  return models;
}
